export const FETCH_ITEM_DETAIL_REQUEST = "FETCH_ITEM_DETAIL_REQUEST";
export const FETCH_ITEM_DETAIL_SUCCESS = "FETCH_ITEM_DETAIL_SUCCESS";
export const FETCH_ITEM_DETAIL_FAILURE = "FETCH_ITEM_DETAIL_FAILURE";
