export const HIDE_NOTIFICATION_BAR = "HIDE_NOTIFICATION_BAR";

export const FETCH_NOTIFICATION_BAR_REQUEST = "FETCH_NOTIFICATION_BAR_REQUEST";
export const FETCH_NOTIFICATION_BAR_SUCCESS = "FETCH_NOTIFICATION_BAR_SUCCESS";
export const FETCH_NOTIFICATION_BAR_FAILURE = "FETCH_NOTIFICATION_BAR_FAILURE";
