export const GGS_FETCH_LIST_ITEMS_REQUEST = "GGS_FETCH_LIST_ITEMS_REQUEST";
export const GGS_FETCH_LIST_ITEMS_SUCCESS = "GGS_FETCH_LIST_ITEMS_SUCCESS";
export const GGS_FETCH_LIST_ITEMS_FAILURE = "GGS_FETCH_LIST_ITEMS_FAILURE";

export const GGS_FETCH_ITEM_DETAIL_REQUEST = "search/GGS_FETCH_ITEM_DETAIL_REQUEST";
export const GGS_FETCH_ITEM_DETAIL_SUCCESS = "search/GGS_FETCH_ITEM_DETAIL_SUCCESS";
export const GGS_FETCH_ITEM_DETAIL_FAILURE = "search/GGS_FETCH_ITEM_DETAIL_FAILURE";

export const GGS_FETCH_TOTAL_ITEMS_REQUEST = "GGS_FETCH_TOTAL_ITEMS_REQUEST";
export const GGS_FETCH_TOTAL_ITEMS_SUCCESS = "GGS_FETCH_TOTAL_ITEMS_SUCCESS";
export const GGS_FETCH_TOTAL_ITEMS_FAILURE = "GGS_FETCH_TOTAL_ITEMS_FAILURE";

export const GGS_TOGGLE_LIKE_ITEM_REQUEST = "GGS_TOGGLE_LIKE_ITEM_REQUEST";
export const GGS_TOGGLE_LIKE_ITEM_SUCCESS = "GGS_TOGGLE_LIKE_ITEM_SUCCESS";
export const GGS_TOGGLE_LIKE_ITEM_FAILURE = "GGS_TOGGLE_LIKE_ITEM_FAILURE";

export const GGS_CHANGE_PAGINATION_ITEMS_CURRENT_PAGE = "GGS_CHANGE_PAGINATION_ITEMS_CURRENT_PAGE";
export const GGS_CHANGE_PAGINATION_ITEMS_PER_PAGE = "GGS_CHANGE_PAGINATION_ITEMS_PER_PAGE";
export const GGS_CHANGE_SEARCH_ITEMS_QUERY = "GGS_CHANGE_SEARCH_ITEMS_QUERY";
export const GGS_CHANGE_SELECT_STATUS_ITEMS = "GGS_CHANGE_SELECT_STATUS_ITEMS";
export const GGS_CHANGE_FIELD_NAME_SORT_BY = "GGS_CHANGE_FIELD_NAME_SORT_BY";
export const GGS_CHANGE_SELECT_TYPE_ITEM = "GGS_CHANGE_SELECT_TYPE_ITEM";
export const GGS_CHANGE_SELECT_BRAND_TYPE_ITEM = "GGS_CHANGE_SELECT_BRAND_TYPE_ITEM";
export const GGS_CHANGE_SELECT_MARKET_ITEM = "GGS_CHANGE_SELECT_MARKET_ITEM";

export const GGS_SHOW_ITEM_DETAIL = "GGS_SHOW_ITEM_DETAIL";
export const GGS_CLOSE_MODAL_ITEM_DETAIL = "GGS_CLOSE_MODAL_ITEM_DETAIL";

export const GGS_TOGGLE_EDITOR_FILTER_RANK = "GGS_TOGGLE_EDITOR_FILTER_RANK";
export const GGS_OPEN_EDITOR_FILTER_RANK = "GGS_OPEN_EDITOR_FILTER_RANK";
export const GGS_CLOSE_EDITOR_FILTER_RANK = "GGS_CLOSE_EDITOR_FILTER_RANK";
export const GGS_CHANGE_TEMP_FILTER_RANK = "GGS_CHANGE_TEMP_FILTER_RANK";
export const GGS_SUBMIT_FILTER_RANK = "GGS_SUBMIT_FILTER_RANK";

export const GGS_TOGGLE_EDITOR_FILTER_PRICE = "GGS_TOGGLE_EDITOR_FILTER_PRICE";
export const GGS_OPEN_EDITOR_FILTER_PRICE = "GGS_OPEN_EDITOR_FILTER_PRICE";
export const GGS_CLOSE_EDITOR_FILTER_PRICE = "GGS_CLOSE_EDITOR_FILTER_PRICE";
export const GGS_CHANGE_TEMP_FILTER_PRICE = "GGS_CHANGE_TEMP_FILTER_PRICE";
export const GGS_SUBMIT_FILTER_PRICE = "GGS_SUBMIT_FILTER_PRICE";

export const GGS_TOGGLE_EDITOR_FILTER_MIN_PRICE = "GGS_TOGGLE_EDITOR_FILTER_MIN_PRICE";
export const GGS_OPEN_EDITOR_FILTER_MIN_PRICE = "GGS_OPEN_EDITOR_FILTER_MIN_PRICE";
export const GGS_CLOSE_EDITOR_FILTER_MIN_PRICE = "GGS_CLOSE_EDITOR_FILTER_MIN_PRICE";
export const GGS_CHANGE_TEMP_FILTER_MIN_PRICE = "GGS_CHANGE_TEMP_FILTER_MIN_PRICE";
export const GGS_SUBMIT_FILTER_MIN_PRICE = "GGS_SUBMIT_FILTER_MIN_PRICE";

export const GGS_TOGGLE_EDITOR_FILTER_MAX_PRICE = "GGS_TOGGLE_EDITOR_FILTER_MAX_PRICE";
export const GGS_OPEN_EDITOR_FILTER_MAX_PRICE = "GGS_OPEN_EDITOR_FILTER_MAX_PRICE";
export const GGS_CLOSE_EDITOR_FILTER_MAX_PRICE = "GGS_CLOSE_EDITOR_FILTER_MAX_PRICE";
export const GGS_CHANGE_TEMP_FILTER_MAX_PRICE = "GGS_CHANGE_TEMP_FILTER_MAX_PRICE";
export const GGS_SUBMIT_FILTER_MAX_PRICE = "GGS_SUBMIT_FILTER_MAX_PRICE";

export const GGS_TOGGLE_EDITOR_FILTER_TIME_AVAILABLE = "GGS_TOGGLE_EDITOR_FILTER_TIME_AVAILABLE";
export const GGS_OPEN_EDITOR_FILTER_TIME_AVAILABLE = "GGS_OPEN_EDITOR_FILTER_TIME_AVAILABLE";
export const GGS_CLOSE_EDITOR_FILTER_TIME_AVAILABLE = "GGS_CLOSE_EDITOR_FILTER_TIME_AVAILABLE";
export const GGS_CHANGE_TEMP_FILTER_TIME_AVAILABLE = "GGS_CHANGE_TEMP_FILTER_TIME_AVAILABLE";
export const GGS_SUBMIT_FILTER_TIME_AVAILABLE = "GGS_SUBMIT_FILTER_TIME_AVAILABLE";

export const GGS_INIT_SETUP_META = "GGS_INIT_SETUP_META";

export const GGS_SWITCH_LAYOUT_PRODUCTS = "GGS_SWITCH_LAYOUT_PRODUCTS";

export const GGS_SAVE_QUERY_SEARCH_ITEM_REQUEST = "GGS_SAVE_QUERY_SEARCH_ITEM_REQUEST";
export const GGS_SAVE_QUERY_SEARCH_ITEM_SUCCESS = "GGS_SAVE_QUERY_SEARCH_ITEM_SUCCESS";
export const GGS_SAVE_QUERY_SEARCH_ITEM_FAILURE = "GGS_SAVE_QUERY_SEARCH_ITEM_FAILURE";

export const GGS_CHANGE_QUERY = "search/GGS_CHANGE_QUERY";

export const GGS_SET_CURRENT_MY_ANALYTIC_ID = "GGS_SET_CURRENT_MY_ANALYTIC_ID";