import {NAME} from "./constants";

export const FETCH_LIST_MY_ANALYTICS_REQUEST = NAME + "/FETCH_LIST_MY_ANALYTICS_REQUEST";
export const FETCH_LIST_MY_ANALYTICS_SUCCESS = NAME + "/FETCH_LIST_MY_ANALYTICS_SUCCESS";
export const FETCH_LIST_MY_ANALYTICS_FAILURE = NAME + "/FETCH_LIST_MY_ANALYTICS_FAILURE";

export const FETCH_REMOVE_MY_ANALYTIC_REQUEST = NAME + "/FETCH_REMOVE_MY_ANALYTIC_REQUEST";
export const FETCH_REMOVE_MY_ANALYTIC_SUCCESS = NAME + "/FETCH_REMOVE_MY_ANALYTIC_SUCCESS";
export const FETCH_REMOVE_MY_ANALYTIC_FAILURE = NAME + "/FETCH_REMOVE_MY_ANALYTIC_FAILURE";