export const GGS_FETCH_ITEM_DETAIL_REQUEST = "GGS_FETCH_ITEM_DETAIL_REQUEST";
export const GGS_FETCH_ITEM_DETAIL_SUCCESS = "GGS_FETCH_ITEM_DETAIL_SUCCESS";
export const GGS_FETCH_ITEM_DETAIL_FAILURE = "GGS_FETCH_ITEM_DETAIL_FAILURE";
