export const HISTORY_FETCH_LIST_ITEMS_REQUEST = "HISTORY_FETCH_LIST_ITEMS_REQUEST";
export const HISTORY_FETCH_LIST_ITEMS_SUCCESS = "HISTORY_FETCH_LIST_ITEMS_SUCCESS";
export const HISTORY_FETCH_LIST_ITEMS_FAILURE = "HISTORY_FETCH_LIST_ITEMS_FAILURE";

export const HISTORY_FETCH_ITEM_DETAIL_REQUEST = "history/HISTORY_FETCH_ITEM_DETAIL_REQUEST";
export const HISTORY_FETCH_ITEM_DETAIL_SUCCESS = "history/HISTORY_FETCH_ITEM_DETAIL_SUCCESS";
export const HISTORY_FETCH_ITEM_DETAIL_FAILURE = "history/HISTORY_FETCH_ITEM_DETAIL_FAILURE";

export const HISTORY_TOGGLE_LIKE_ITEM_REQUEST = "HISTORY_TOGGLE_LIKE_ITEM_REQUEST";
export const HISTORY_TOGGLE_LIKE_ITEM_SUCCESS = "HISTORY_TOGGLE_LIKE_ITEM_SUCCESS";
export const HISTORY_TOGGLE_LIKE_ITEM_FAILURE = "HISTORY_TOGGLE_LIKE_ITEM_FAILURE";

export const HISTORY_CHANGE_PAGINATION_ITEMS_CURRENT_PAGE = "HISTORY_CHANGE_PAGINATION_ITEMS_CURRENT_PAGE";
export const HISTORY_CHANGE_PAGINATION_ITEMS_PER_PAGE = "HISTORY_CHANGE_PAGINATION_ITEMS_PER_PAGE";
export const HISTORY_CHANGE_SEARCH_ITEMS_QUERY = "HISTORY_CHANGE_SEARCH_ITEMS_QUERY";
export const HISTORY_CHANGE_FIELD_NAME_SORT_BY = "HISTORY_CHANGE_FIELD_NAME_SORT_BY";
export const HISTORY_CHANGE_SELECT_TYPE_ITEM = "HISTORY_CHANGE_SELECT_TYPE_ITEM";
export const HISTORY_CHANGE_SELECT_BRAND_TYPE_ITEM = "HISTORY_CHANGE_SELECT_BRAND_TYPE_ITEM";

export const HISTORY_SHOW_ITEM_DETAIL = "HISTORY_SHOW_ITEM_DETAIL";
export const HISTORY_CLOSE_MODAL_ITEM_DETAIL = "HISTORY_CLOSE_MODAL_ITEM_DETAIL";

export const HISTORY_TOGGLE_EDITOR_FILTER_RANK = "HISTORY_TOGGLE_EDITOR_FILTER_RANK";
export const HISTORY_OPEN_EDITOR_FILTER_RANK = "HISTORY_OPEN_EDITOR_FILTER_RANK";
export const HISTORY_CLOSE_EDITOR_FILTER_RANK = "HISTORY_CLOSE_EDITOR_FILTER_RANK";
export const HISTORY_CHANGE_TEMP_FILTER_RANK = "HISTORY_CHANGE_TEMP_FILTER_RANK";
export const HISTORY_SUBMIT_FILTER_RANK = "HISTORY_SUBMIT_FILTER_RANK";

export const HISTORY_TOGGLE_EDITOR_FILTER_PRICE = "HISTORY_TOGGLE_EDITOR_FILTER_PRICE";
export const HISTORY_OPEN_EDITOR_FILTER_PRICE = "HISTORY_OPEN_EDITOR_FILTER_PRICE";
export const HISTORY_CLOSE_EDITOR_FILTER_PRICE = "HISTORY_CLOSE_EDITOR_FILTER_PRICE";
export const HISTORY_CHANGE_TEMP_FILTER_PRICE = "HISTORY_CHANGE_TEMP_FILTER_PRICE";
export const HISTORY_SUBMIT_FILTER_PRICE = "HISTORY_SUBMIT_FILTER_PRICE";

export const HISTORY_TOGGLE_EDITOR_FILTER_HISTORICAL_DAY = "HISTORY_TOGGLE_EDITOR_HISTORICAL_DAY";
export const HISTORY_OPEN_EDITOR_FILTER_HISTORICAL_DAY = "HISTORY_OPEN_EDITOR_FILTER_HISTORICAL_DAY";
export const HISTORY_CLOSE_EDITOR_FILTER_HISTORICAL_DAY = "HISTORY_CLOSE_EDITOR_FILTER_HISTORICAL_DAY";
export const HISTORY_CHANGE_TEMP_FILTER_HISTORICAL_DAY = "HISTORY_CHANGE_TEMP_FILTER_HISTORICAL_DAY";
export const HISTORY_SUBMIT_FILTER_HISTORICAL_DAY = "HISTORY_SUBMIT_FILTER_HISTORICAL_DAY";

export const HISTORY_TOGGLE_EDITOR_FILTER_TIME_AVAILABLE = "HISTORY_TOGGLE_EDITOR_FILTER_TIME_AVAILABLE";
export const HISTORY_OPEN_EDITOR_FILTER_TIME_AVAILABLE = "HISTORY_OPEN_EDITOR_FILTER_TIME_AVAILABLE";
export const HISTORY_CLOSE_EDITOR_FILTER_TIME_AVAILABLE = "HISTORY_CLOSE_EDITOR_FILTER_TIME_AVAILABLE";
export const HISTORY_CHANGE_TEMP_FILTER_TIME_AVAILABLE = "HISTORY_CHANGE_TEMP_FILTER_TIME_AVAILABLE";
export const HISTORY_SUBMIT_FILTER_TIME_AVAILABLE = "HISTORY_SUBMIT_FILTER_TIME_AVAILABLE";

export const HISTORY_INIT_SETUP_META = "HISTORY_INIT_SETUP_META";

export const HISTORY_SWITCH_LAYOUT_PRODUCTS = "HISTORY_SWITCH_LAYOUT_PRODUCTS";