export const FETCH_STATISTIC_OVERVIEW_REQUEST = "FETCH_STATISTIC_OVERVIEW_REQUEST";
export const FETCH_STATISTIC_OVERVIEW_SUCCESS = "FETCH_STATISTIC_OVERVIEW_SUCCESS";
export const FETCH_STATISTIC_OVERVIEW_FAILURE = "FETCH_STATISTIC_OVERVIEW_FAILURE";

export const FETCH_STATISTIC_HAS_RANK_REQUEST = "FETCH_STATISTIC_HAS_RANK_REQUEST";
export const FETCH_STATISTIC_HAS_RANK_SUCCESS = "FETCH_STATISTIC_HAS_RANK_SUCCESS";
export const FETCH_STATISTIC_HAS_RANK_FAILURE = "FETCH_STATISTIC_HAS_RANK_FAILURE";

export const STATISTIC_CHANGE_SELECT_DAYS = "overview/STATISTIC_CHANGE_SELECT_DAYS";