export const TOGGLE_COLLAPSE_SIDEBAR = "TOGGLE_COLLAPSE_SIDEBAR";
export const CLOSE_LIMITED_OFFER = 'CLOSE_LIMITED_OFFER'
export const OPEN_LIMITED_OFFER = 'OPEN_LIMITED_OFFER'
export const TOGGLE_UPGRADE_POPUP='TOGGLE_UPGRADE_POPUP'

export const HIDE_OFFER = 'HIDE_OFFER'
