export const FETCH_STATISTIC_UPDATE_REQUEST = "FETCH_STATISTIC_UPDATE_REQUEST";
export const FETCH_STATISTIC_UPDATE_SUCCESS = "FETCH_STATISTIC_UPDATE_SUCCESS";
export const FETCH_STATISTIC_UPDATE_FAILURE = "FETCH_STATISTIC_UPDATE_FAILURE";
