exports.EVERY_MINUTE = '* * * * *'
exports.EVERY_FIVE_MINUTES = '*/5 * * * *'
exports.EVERY_HOUR = '0 * * * *'
exports.EVERY_THREE_HOURS = '0 */3 * * *'
exports.EVERY_SIX_HOURS = '0 */6 * * *'
exports.EVERY_TWELVE_HOURS = '0 */12 * * *'
exports.EVERY_DAY = '0 0 * * *'
