exports.GET_HEARTBEAT = 'GET_HEARTBEAT'

exports.NEW_USER_REGISTER = 'NEW_USER_REGISTER'
exports.NEW_REGISTER_TRIAL = 'NEW_REGISTER_TRIAL'
exports.NEW_SUBSCRIPTION_AUTO = 'NEW_SUBSCRIPTION_AUTO'
exports.NEW_SUBSCRIPTION_MANUAL = 'NEW_SUBSCRIPTION_MANUAL'

exports.NEW_ACCESS_TOKEN = 'NEW_ACCESS_TOKEN'

exports.BILL_COMPLETED = 'BILL_COMPLETED'
exports.BILL_CREATED = 'BILL_CREATED'

exports.USER_CHANGE_MEMBERSHIP = "USER_CHANGE_MEMBERSHIP"

